// <auto-generated />
using System;
using KooliProjekt.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KooliProjekt.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KooliProjekt.Application.Data.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mudel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Numbrimark")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Tootja")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Numbrimark")
                        .IsUnique();

                    b.ToTable("Autos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mudel = "Corolla",
                            Numbrimark = "123ABC",
                            Tootja = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Mudel = "320",
                            Numbrimark = "555BMW",
                            Tootja = "BMW"
                        });
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Operatsioon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Kuupäev")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Maksumus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Staatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TöötajaId")
                        .HasColumnType("int");

                    b.Property<int>("TüüpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutoId");

                    b.HasIndex("TöötajaId");

                    b.HasIndex("TüüpId");

                    b.ToTable("Operatsioonid");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoId = 1,
                            Kuupäev = new DateTime(2025, 12, 9, 22, 23, 24, 131, DateTimeKind.Local).AddTicks(4146),
                            Maksumus = 35m,
                            Staatus = "Ootel",
                            TöötajaId = 2,
                            TüüpId = 1
                        },
                        new
                        {
                            Id = 2,
                            AutoId = 2,
                            Kuupäev = new DateTime(2025, 12, 10, 22, 23, 24, 131, DateTimeKind.Local).AddTicks(4197),
                            Maksumus = 50m,
                            Staatus = "Tegemisel",
                            TöötajaId = 2,
                            TüüpId = 2
                        });
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.OperatsiooniTyyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kirjeldus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nimi")
                        .IsUnique();

                    b.ToTable("OperatsiooniTüübid");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kirjeldus = "Mootoriõli vahetus",
                            Nimi = "Õlivahetus"
                        },
                        new
                        {
                            Id = 2,
                            Kirjeldus = "Rehvide vahetus komplektiga",
                            Nimi = "Rehvide vahetus"
                        });
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Töötaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Roll")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Töötajad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            Nimi = "Admin",
                            Roll = "Administraator"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jaan@example.com",
                            Nimi = "Jaan",
                            Roll = "Töötaja"
                        });
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Operatsioon", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Auto", "Auto")
                        .WithMany()
                        .HasForeignKey("AutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KooliProjekt.Application.Data.Töötaja", "Töötaja")
                        .WithMany()
                        .HasForeignKey("TöötajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KooliProjekt.Application.Data.OperatsiooniTyyp", "Tüüp")
                        .WithMany()
                        .HasForeignKey("TüüpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auto");

                    b.Navigation("Töötaja");

                    b.Navigation("Tüüp");
                });
#pragma warning restore 612, 618
        }
    }
}
